# NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")

resources:
  repositories:
    - repository: self
      trigger: none

variables:
  azureServiceConnection: "azure-connection"
  subscriptionId: "1f3c249c-a2bc-4d1e-b042-0c6658fe0ba3"
  resourceGroup: "rg-az400-container-webapi"
  location: "eastus"

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploy ACR using Bicep
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: $(azureServiceConnection)
              subscriptionId: $(subscriptionId)
              action: "Create Or Update Resource Group"
              resourceGroupName: "$(resourceGroup)"
              location: "$(location)"
              templateLocation: "Linked artifact"
              csmFile: "infra/acr.bicep"
              deploymentMode: "Incremental"
              deploymentOutputs: "outputJson"
          - task: PowerShell@2
            displayName: Parse Bicep Output
            inputs:
              targetType: "inline"
              script: |
                $var=ConvertFrom-Json '$(outputJson)'
                $value=$var.acrLoginServer.value
                Write-Host "##vso[task.setvariable variable=acrLoginServer;]$value"
          - task: Docker@0
            displayName: "Build the docker image"
            inputs:
              azureSubscription: $(azureServiceConnection)
              azureContainerRegistry: $(acrLoginServer)
              dockerFile: "Dockerfile"
              defaultContext: false
              context: $(Build.SourcesDirectory)
              includeLatestTag: true
              imageName: webapi/web:$(Build.BuildId)
          - task: Docker@0
            displayName: "Push the docker images"
            inputs:
              azureSubscription: $(azureServiceConnection)
              azureContainerRegistry: $(acrLoginServer)
              action: "Push an image"
              imageName: webapi/web:$(Build.BuildId)
              includeLatestTag: true
